export const patientSchema = {
  title: 'Patient Schema',
  version: 1,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 100 },
    shortName: { type: 'string' },
    firstName: { type: 'string' },
    middleName: { type: 'string' },
    lastName: { type: 'string' },
    birthDate: { type: 'string' },
    gender: { type: 'string', enum: ['M', 'F', 'U'] },
    createdAt: { type: 'string' },
    updatedAt: { type: 'string' },
    deleted: { type: 'boolean' },
  },
  required: [
    'id',
    'shortName',
    'birthDate',
    'gender',
    'createdAt',
    'updatedAt',
    'deleted',
  ],
}

export const reportSchema = {
  title: 'Report Schema',
  version: 1,
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 100 },
    patientId: { type: 'string', maxLength: 100 },
    modality: { type: 'string' },
    studyDescription: { type: 'string' },
    description: { type: 'string' },
    conclusion: { type: 'string' },
    createdAt: { type: 'string' },
    updatedAt: { type: 'string' },
    deleted: { type: 'boolean' },
  },
  required: [
    'id',
    'patientId',
    'modality',
    'studyDescription',
    'content',
    'conclusion',
    'createdAt',
    'updatedAt',
    'deleted',
  ],
}
